### ISSUE TITLE
createTokenRequest without key option

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#21]
In the Ably Ruby library when calling [createTokenRequest](https://github.com/ably/ably-ruby/blob/master/lib/ably/auth.rb#L192), if an API key has been specified in the constructor, then there is no need to specify a key ID in the createTokenRequest method.  Given most people will only issue tokens for the set up API key and we treat API keys as opaque (i.e. key ID is not really relevant), I recommend we change the [createTokenRequest](https://github.com/ably/ably-js/blob/master/common/lib/client/auth.js#L297-L326) in the JS client library so that:

* Passing in an empty hash is valid so long as Basic Auth is being used
* instead of key_id & key_value options in the hash, we should really just support a key option.

**Comment by mattheworiordan** [comment]
I see also that the keyValue does not behave like it should in the documentation:
```
* - keyValue:      (optional) the secret value of the key; if not
	 *                  specified, a key passed in constructing the Rest interface will be used; or
	 *                  if no key is available, a token request callback or url will be used.
```

I get the error 'No key specified'

**Comment by mattheworiordan** [comment]
One more issue, the token request Hash that is returned has a Hash object for the capability element, but it should be a Stringified JSON object.  I believe if you receive a JSON capability the client library should be default Stringify it.  Example request:

```javascript
new Ably.Realtime({ key: apiKey }).auth.createTokenRequest(
        { keyId: keyId, keyValue: keyValue },
        { "ttl": 600, "capability": { "*":["*"] } }, function(token) {
          console.log(token);
        )

'{
  "id": "xVLyHw.lwnKYQ",
  "ttl": 600,
  "capability": {
    "*": [
      "*"
    ]
  },
  "timestamp": 1427235284,
  "nonce": "0452151051722466",
  "mac": "XslUpDsA5OQ7PSMKcrdb3IpMXNJg5VPXMyjVAgwsKyc="
}'
```

**Comment by paddybyers** [comment]
Resolved

**Comment by mattheworiordan** [comment]
I do not believe this is fixed unfortunately, see https://github.com/ably/docs/commit/7c60e3bd1b9024b6d2833a98d0418dd2bc7dce89 which I had to do now to get `createTokenRequest` to work.  I was getting an error "missing key".

**Comment by mattheworiordan** [comment]
See https://jsbin.ably.io/anadag/3/edit, this is not fixed.
Error is `Error Error {message: "No key specified"}`

**Comment by paddybyers** [comment]
@SimonWoolf : could you have a look at this please?

**Comment by SimonWoolf** [comment]
@mattheworiordan Addressed both in https://github.com/ably/ably-js/pull/83. Good spot re stringifying the createTokenRequest -- without that the capability part of the signText was just "[object Object]", which produces an hmac that realtime happily validates without comment. (Which is only a security risk if realtime actually acts on capabilities given as objects rather than JSON strings - I'll open an issue in realtime to check that with Paddy)

**Comment by paddybyers** [comment]
> Which I guess is only a security risk if realtime actually acts on capabilities given as objects rather than JSON strings

Hopefully ok: 

https://github.com/ably/realtime/blob/master/common/lib/security/authmgr.js#L391-L392
