### ISSUE TITLE
Get `import Ably from 'ably'` working

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#426]
Currently for ES6 import (in browser envs) you need to do `import Ably from 'ably/browser/static/ably-commonjs.js'`. Would be nice if you could do `import Ably from 'ably'`. (Shouldn't https://github.com/ably/ably-js/blob/master/package.json#L10-L12 in theory autoresolve that? if so need to figure out why that doesn't work)

**Comment by wichert** [comment]
To use flow with Ably you currently also have to do things like this:

```
import type Channel from 'ably/common/lib/client/channel'
import type ConnectionStateChange from 'ably/common/lib/client/connectionstatechange'
```

it would be nice if that could be improves as well

**Comment by funkyboy** [comment]
@SimonWoolf I think this is solved. https://github.com/ably/ably-js#TypeScript
Reopen if not.

**Comment by SimonWoolf** [comment]
> I think this is solved. https://github.com/ably/ably-js#TypeScript

For typescript yes, for normal es6 (in browser environments) I believe still not.

related: the 'proper' (albeit labour-intensive) solution would be to port everything (both node and browserside) to es6 modules and use that as a base for further transpilation where necessary. relataed: https://github.com/ably/ably-js/issues/477
